### ISSUE TITLE
Flag doesn`t work 

### ISSUE THREAD

**Issue by gtarashuk** [basdvries/BDVCountryNameAndCode#6]
Maybe this is not the best title but countryFlagForCurrentLocale does not work for me.

Cause 
`<[[NSLocale currentLocale] displayNameForKey:NSLocaleCountryCode value:[[NSLocale currentLocale] objectForKey:NSLocaleCountryCode]]>` - returns localized name of Country. For me it was Ukrainian so your method returns wrong name of image.

I purpose you to use your method to get name of country from your plist file - so you will always receive right name.

**Comment by basdvries** [comment]
Closing this issue as it doesn't provide enough debugging information. Feel free to add more information and I'll reopen this.
